### ISSUE TITLE
Refactorings

### ISSUE THREAD

**Issue by FacoBackup** [FacoBackup/pine-engine#92]
## Tasks
- [x] Request processing should be done on main thread, no need for a new thread that will only fire on demand
- [x] Request processing should be an editor thing, not an engine thing

## Logging and console view
- [x] Console view should consume from a list of messages generated by the editor itself and not low level logs of errors and other stuff
- [x] Use indexed loop instead of iterator loop to prevent concurrent modification errors
- [x] Add option to clear log pile
